### ISSUE TITLE
Any updates on the outage?

### ISSUE THREAD

**Issue by Ronxlotl** [PenguinMod/PenguinMod-Home#60]

**Comment by Ronxlotl** [comment]
the server came back online but i got no response

**Comment by T-ufy** [comment]
its sorta on and off

**Comment by whistler12** [comment]
![error1033](https://github.com/PenguinMod/PenguinMod-Home/assets/88686819/69f5107f-c39f-4feb-ba45-f58ee370fe73)

**Comment by JeremyGamer13** [comment]
server seems to be more stable now, any downtime or weird behavior from now seems to be caused by long server tasks like sending update messages to all users or a bug we are trying to figure out where certain projects cause long upload times before eventually uploading a broken project (which should be a seperate issue if you want to make one)
